### ISSUE TITLE
Create systemd service

### ISSUE THREAD

**Issue by angel12** [cameronbackus/doPBX#2]
I have had an issue with things not starting correctly on reboots, and think I have fixed it in the install script by adding this at the end: 

```
#Systemd service creation
cat > /etc/systemd/system/freepbx.service << EOF
[Unit]
Description=FreePBX VoIP Server
After=mariadb.service
 
[Service]
Type=oneshot
RemainAfterExit=yes
ExecStart=/usr/sbin/fwconsole start
ExecStop=/usr/sbin/fwconsole stop
 
[Install]
WantedBy=multi-user.target
EOF

#Enable service to start automatically
systemctl enable freepbx.service

#Start service
systemctl start freepbx
```
as found here: http://wiki.freepbx.org/display/FOP/Example+systemd+startup+script+for+FreePBX
I have tested this new script on one machine, so I would test it some more if you have the ability to test and verify. I saw someone else on your blog had the same issue, so I figure this might help most people on DO use freepbx easily ;)

**Comment by ffs123** [comment]
Thank you. Your solution is great.

**Comment by cameronbackus** [comment]
Included these changes in a previous update to the script, thank you very much!
