### ISSUE TITLE
Change asterisk to use bundled libpj

### ISSUE THREAD

**Issue by Faeranne** [cameronbackus/doPBX#4]
the current version of libpj that the script uses throws a bug half way through installing asterisk.
```‘PJ_SSL_SOCK_MAX_CIPHERS’ undeclared```
https://blogs.asterisk.org/2016/03/16/asterisk-13-8-0-now-easier-pjsip-install-method/ recommends using the `--with-pjproject-bundled` flag when compiling.

**Comment by cameronbackus** [comment]
Thank you very much both,

This has now been merged into the master copy!
